version: "3"
services:
  mysql:
    build: .
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      #- "storage:/var/lib/mysql"
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - "./initdb/:/docker-entrypoint-initdb.d/"
#volumes:
#  storage:
